### ISSUE TITLE
Rate limiting

### ISSUE THREAD

**Issue by saikat** [Bernie-2016/ground-control#149]

**Comment by jlegrone** [comment]
We definitely should rate limit event creation requests. What else should we be limiting?

**Comment by saikat** [comment]
We need to rate limit event creations and phone call assignments being created to avoid a bot going in and just programmatically clicking "did not respond, next" over and over again.  Giving this to Will.

**Comment by wblankenship** [comment]
Lucky for us, there is a middleware that can do this for us :smile:

https://www.npmjs.com/package/express-rate-limit
