### ISSUE TITLE
Add authentication

### ISSUE THREAD

**Issue by saikat** [Bernie-2016/ground-control#19]
We should not make it possible fro just anyone to hit this endpoint and start making maestro calls.

**Comment by saikat** [comment]
- make signup/login component - 
			- Enter your e-mail to get started
				- Has all required fields? Set a password
				- Missing required fields? Show the big vol signup form. 
				- Has account? Enter password to log in.
		 		- add session store
				- send session info down to routes
		- Make currentUser be the current logged in user
			- Return null for viewer if not logged in, otherwise return viewer

**Comment by wblankenship** [comment]
Can we just use oauth?

**Comment by saikat** [comment]
I don't believe Blue State Digital (which is what powers go.berniesanders.com) has OAuth support, and I'd like to make it so people who have already made an account on berniesanders.com can use that account to login here.  They do have an API to "check_credentials" and "create_account" which is what I'm currently planning to use.

**Comment by wblankenship** [comment]
Ah, it sounded like we were rolling our own auth system. So will they still need to create an account here? Or when they try to create an account on ground-control, will it redirect them to go.berniesanders.com?

**Comment by saikat** [comment]
The idea is when the create an account on ground-control, it actually
authenticates against go.berniesanders.com, but keeps them on ground
control.  The downside is that if they go to go.berniesanders.com, they'd
need to re-authenticate, but that's ok -- there's not much you can do there
anyway other than manage events.
