### ISSUE TITLE
Configure DNS records for berniesanders.com to allow transparent email sending via Mailgun

### ISSUE THREAD

**Issue by jlegrone** [Bernie-2016/ground-control#191]
Instructions can be found [here](https://documentation.mailgun.com/faqs.html#email-clients-says-sent-via-mailgun-us-with-messages-i-send-how-do-i-get-rid-of-this).

**Comment by jlegrone** [comment]
After our DNS records and Mailgun account are configured correctly, we will also have to set the `MAILGUN_DOMAIN` environment variable to our new Mailgun domain.

**Comment by saikat** [comment]
There is an official campaign mailgun.  Reminder to myself that I should switch it to use that.

**Comment by schneidmaster** [comment]
Official campaign mailgun is set up on the mg.berniesanders.com domain -- it can't be on the root berniesanders.com domain because that's used for our (staffers') @berniesanders.com email addresses.

**Comment by saikat** [comment]
This should be using the official campaign MG details now, but someone needs to check it's doing the right thing.
