### ISSUE TITLE
Job to remove assigned calls is running every minute instead of hour

### ISSUE THREAD

**Issue by saikat** [Bernie-2016/ground-control#192]
I haven't checked in heroku, but at least locally.

**Comment by wblankenship** [comment]
Right. So we want it to remove all calls that have existed for > 1 hour. If we run it every hour, we are going to have a precision of ~2hours. Calls that get logged immediately after a cleanup will survive the next cleanup an hour later and stay claimed for nearly 2 hours.

We could probably scale the job back to run every 10 minutes or so.

**Comment by saikat** [comment]
Yup, exactly.  Though to be honest, minutely isn't so bad, it's a quick
job.  Let's just close this.

**Comment by wblankenship** [comment]
From slack, it sounds like this may be coming in your next PR :smile:

**Comment by saikat** [comment]
Yup, closed.
