### ISSUE TITLE
Add frontend event deletion confirmation logic, and figure out what kind of confirmation is best

### ISSUE THREAD

**Issue by jlegrone** [Bernie-2016/ground-control#219]
Right now you get a modal requesting that you type 'DELETE' in an input and then click the confirm delete button to delete events. Perhaps we could safely go with something like "Type 'd' to confirm delete, any other key to cancel".

**Comment by jlegrone** [comment]
Alternatively we could perform deletions without confirmation, but with the option to undo the previous action in a SnackBar.

**Comment by saikat** [comment]
I changed this so that you only get the DELETE prompt if you are deleting more than 5.
