### ISSUE TITLE
For 'show in search results', have an option for 'use event type settings' or show the actual setting from the event type

### ISSUE THREAD

**Issue by saikat** [Bernie-2016/ground-control#277]
Currently for events that use event type settings, it displays no, but for a lot of events the default is yes.  Would be ideal to possibly set this based on the event type's setting.

**Comment by saikat** [comment]
This is actually more urgent than I originally thought.  Submitting an event will set a previously public event to private if it was using the default event type settings.

**Comment by saikat** [comment]
So let's just make this a dropdown for now.  I don't know what integer refers to what.

**Comment by jlegrone** [comment]
Close the issue when we confirm which values do what.
