### ISSUE TITLE
Mac OS X El Capitan install: postgres needs additional folders created

### ISSUE THREAD

**Issue by datapolitical** [Bernie-2016/ground-control#303]
Apple deleted a couple of folders during the update from Yosemite that postgres needs to operate. Simply create the following before running ./setup-osx and you should be good to go. 

mkdir /usr/local/var/postgres/pg_logical
mkdir /usr/local/var/postgres/pg_logical/mappings
mkdir /usr/local/var/postgres/pg_logical/snapshots

See: http://stackoverflow.com/questions/32935520/dropdb-database-removal-failed-error-checkpoint-request-failed

**Comment by regardsrajesh** [comment]
worked for me... thanks...!
