### ISSUE TITLE
User report: Creating an event via admin even when the checkbox for 'needs further review' isn't checked puts the event in the approval queue

### ISSUE THREAD

**Issue by saikat** [Bernie-2016/ground-control#313]

**Comment by jlegrone** [comment]
I cannot duplicate this. Events created with the form will not show up until the next sync occurs (unless we trigger an immediate sync). Perhaps the user did not see the event in approved events and assumed it was in the approval queue?

**Comment by saikat** [comment]
You tried it on production?

**Comment by saikat** [comment]
Yeah I jsut tried.  My guess is they are not using the admin url, let me double check.

**Comment by saikat** [comment]
I also could not replicate.
