### ISSUE TITLE
Plivo dials don't seem to be going through

### ISSUE THREAD

**Issue by saikat** [Bernie-2016/ground-control#320]
I've put in production credentials and tried hardcoding in my number, but it fails on localhost with "unavailable" and on production by just attempting but without hang-up working.  I only debugged lightly, so not totally sure what might be going on here.  The other bit is that in Safari, the button shows up (presumably because flash is available), but clicking it fails with a message implying that the application is not logged in.

**Comment by al3x** [comment]
Unless it's been approved for outbound calls by one of their agents it won't work for anything except a test SIP number.

**Comment by al3x** [comment]
Will look into Safari issue, which seems unrelated.

**Comment by al3x** [comment]
Support ticket has been filed with Plivo for the referencing the `bernie2016151225174042` endpoint owned by `saikat-bernie`, requesting approval for outgoing domestic calls.

**Comment by al3x** [comment]
Issue resolved through Plivo support. Fix required specifying caller ID in the Plivo admin interface for the "Direct Dial" app.
