### ISSUE TITLE
Loading organize.berniesanders.com is SO SLOW

### ISSUE THREAD

**Issue by saikat** [Bernie-2016/ground-control#322]
Look into serverside rendering

**Comment by jlegrone** [comment]
I think a big part of this is the redirects for unauthenticated users. We may want to set up redirects in server.js to avoid loading the whole app before a redirect occurs, and prerender the landing page.

Server side rendering for the whole app is possible, but feeding in data for non-static views is a bit of a hurdle.

**Comment by saikat** [comment]
React server side rendering is what I meant.

**Comment by saikat** [comment]
Ok I think I know the issue here because it seemed ridiculously slow for loading what is a big payload but not gigantic.  I believe we can solve most of this problem with better cloudflare caching, so I'm going to do that first.  We'll hold off on the SSR until later.

**Comment by saikat** [comment]
Ok so this is going to be our solution, I believe.  I don't know how to do all of this, but it should work.

- [x] Minify app.js as part of the production build process
- [x] Turn off gzip on the cloudflare end because it's hard for us to control that endpoint.  We are switching to keeping cloudflare as our DNS server and as our SSL termination endpoint, but that's it.

And then either of the bottom two:
- [ ] Compress our application with gzip as part of the build process.  https://github.com/webpack/compression-webpack-plugin seems to work (I used it), but I don't know how to serve the resulting .gz file from express correctly (I assume some header needs to be set).  But app.js, when gzipped, goes down to 1 MB, which is way more reasonable.

- [ ] Set up CloudFront.  CloudFront has its own gzipping mechanism and we then just need to add a step in our build process to invalidate the cloudfront cache when we deploy.  This solution is better than the above but maybe more complicated (probably not for someone who knows cloudfront - @bahoo ?)

**Comment by bahoo** [comment]
>  Compress our application with gzip as part of the build process. https://github.com/webpack/compression-webpack-plugin seems to work (I used it), but I don't know how to serve the resulting .gz file from express correctly (I assume some header needs to be set).

Correct, tell the browser what encoding you're sending, then what to do with that file once it's decoded / decompressed:

    Content-Encoding: gzip
    Content-Type: text/javascript

I am green with Express but this seems like a fine approach: http://51elliot.blogspot.com/2012/08/serve-gzipped-files-with-expressjs.html

> Set up CloudFront. CloudFront has its own gzipping mechanism and we then just need to add a step in our build process to invalidate the cloudfront cache when we deploy. This solution is better than the above but maybe more complicated (probably not for someone who knows cloudfront - @bahoo ?)

Happy to help. CloudFront + gzipping did the trick for map.berniesanders.com but I wonder if we can get some of the same goodness out of CloudFlare. It'd be easy to re-purpose the map's deploy script but making that play nice with Heroku's build process / buildpack API is new turf for me, and might be a lot to bite off.

See a slightly scrubbed deploy script here; the good stuff for us starts at line 69: https://gist.github.com/bahoo/fdeaf0aaae9d08552dd7

Meanwhile I'm going to setup a CloudFlare account (as I'm more familiar with Varnish, which it uses under the hood) and see what I can learn.

**Comment by saikat** [comment]
@bahoo had a great idea -- let's just make app.js have some sort of hash appended to it in our deploy process.  Then, I can ask the people who run our cloudflare account to just set up a high TTL cache for us on /assets/ only and not for index.html and we'll invalidate the cache by deploying different named assets every time.  I've used this approach in the past and it's actually the best way to ensure cache invalidation on deploys anyway.

**Comment by saikat** [comment]
I just realized that I was shipping the sourcemaps, and that was the major
cause of this.  Took that out, filesize is down to about 550k on the wire,
so this is no longer as hugely important.  But still, would be good to do
the build step to hash app.js.

**Comment by bahoo** [comment]
Alright! 4.4MB's did seem pretty hyooge.

**Comment by saikat** [comment]
@bahoo would you be interested in looking into doing the production deploy hashing thing? Then I can just ask Gabe to turn on caching on cloudflare on /assets/ and we will be golden.  I set the maxAge on index.html to 0.  I think the things left to do in deploy are:

- [ ] Create a hash of some sort
- [ ] Change the index.mustache template to not hardcode script to /assets/js/app.js and instead make that a templated variable
- [ ] Pass in the hashed variable to mustache when creating index.html (app.js for dev, app-<hash>.js for prod)
- [ ] Make webpack output to app-<hash>.js when it creates the bundle.

The script doing all the building is 'postinstall' inside package.json.

**Comment by bahoo** [comment]
I'd want to run this by someone a little more Express-savvy than me but seems like this could be a big help here: https://github.com/techjacker/node-version-assets
