### ISSUE TITLE
Add automatic redirect to SSL

### ISSUE THREAD

**Issue by saikat** [Bernie-2016/ground-control#358]

**Comment by al3x** [comment]
This will likely require using the multi buildpack, in turn using the nginx buildpack, to implement the redirect as per [this post](https://github.com/gregburek/heroku-tls-auth-nginx-sample).

Alternately, we can implement the cheesy way by doing this at the Express level with [a module like this](https://github.com/nodenica/node-heroku-ssl-redirect).

**Comment by saikat** [comment]
Ah I should provide some background.

So currently, we have Cloudflare terminating our SSL.  It seems like this is working fine, and Cloudflare passes along a header supposedly that tells us the protocol of the initial request to organize.berniesanders.com (since the Cloudflare -> Heroku link is HTTP).  

Info on headers injected by CloudFlare
https://support.cloudflare.com/hc/en-us/articles/200170986-How-does-CloudFlare-handle-HTTP-Request-headers-

I believe the last one mentioned (CF-Visitor) is the one we are looking for.
