### ISSUE TITLE
Require a delete message to be sent to event host when events are deleted

### ISSUE THREAD

**Issue by jlegrone** [Bernie-2016/ground-control#369]

**Comment by craiggrella** [comment]
Text for deleting event:
When event is canceled by host:
This event has been cancelled by the host.

You can find other events in your area by searching our event map at map.berniesanders.com or by visiting Bernie 2016 event central at http://berniesanders.com/events.

When there, enter your zip code and find events in your area.

Thank you for your support!

Events Team
Bernie 2016

**Comment by craiggrella** [comment]
Text for deleting event:
When event is a fundraiser:

Thank you for submitting your event to Bernie 2016 Events Central.

Please note we do not approve fundraisers without prior campaign contact.

You can resubmit your event following guidelines at BernieSanders.com/plan.

Thank you again for your support and for helping to spread Bernie’s message!

Craig Grella
Bernie 2016
