### ISSUE TITLE
Figure out why we can't approve one event in Florida

### ISSUE THREAD

**Issue by saikat** [Bernie-2016/ground-control#371]
I suspect it's because he URL is too long and I need to stop sending params in the querystring when it's a POST.  We need to rewrite generateBSDURL to test this out.

This is the event:
4vrmm

**Comment by saikat** [comment]
Look at generateBSDURL in bsd.js

**Comment by saikat** [comment]
https://www.bluestatedigital.com/page/api/doc#-----------------Generating-an-api_mac-------------

**Comment by jlegrone** [comment]
https://papertrailapp.com/systems/bernie-ground-control/events?t=1452587911&ut=Jan+12+03%3A38%3A31

**Comment by saikat** [comment]
I think this is fixed now.
