### ISSUE TITLE
Incorrect attendee count on some events

### ISSUE THREAD

**Issue by al3x** [Bernie-2016/ground-control#403]
Some phonebanking events are being displayed as having zero attendees even though they're at capacity.

[Screenshot of one such event](https://berniebuilders.slack.com/files/elijah/F0HSKTRRQ/screenshot_2016-01-06_at_22.35.36.png).

This was reported by @elijah in the #ground-control Slack channel.

**Comment by mrb** [comment]
I'm checking this out

**Comment by saikat** [comment]
Seems to be all of them are 0.  That makes this a high priority in my mind.

**Comment by amundhov** [comment]
+1. Reported this as well when I started phone-banking. This bug is making me hesitant when making phone calls, since you don't want to pitch an event which is not available.

@mrb:  Did you find anything for a hotfix?
