### ISSUE TITLE
Create handlebars template for event creation form

### ISSUE THREAD

**Issue by jlegrone** [Bernie-2016/ground-control#424]
We should merge `create_event.html` and `create_event_public.html` from `src/frontend/public/admin/events` into a template file to avoid unnecessary duplication of code. There are several key differences that must be preserved.

The template will be compiled and served from `src/backend/server.js`. Look for `app.get('/events/create'...` and `app.get('/admin/events/create'...` declarations to modify.

**Comment by nkammah** [comment]
PR available here : https://github.com/Bernie-2016/ground-control/pull/426
