### ISSUE TITLE
Make sure all events created via /admin bypass the approval queue

### ISSUE THREAD

**Issue by saikat** [Bernie-2016/ground-control#452]

**Comment by craiggrella** [comment]
only if they meet other criteria like:
they do not mention fundraising
they do not mention merchandise sales, official or unofficial
they do not mention ticket sales or ask people to pay for access to the event
they do not ask people to bring marijuana with them, regardless of the state in which the event takes place

Those are all items legal has asked us to remove when we see them

**Comment by jlegrone** [comment]
Still only enabling this specifically for Phonebank and Jan 23rd event types. Let me know if we need others. Up to 20 events can be created at a time for logged in users.
