### ISSUE TITLE
Updating an event to be private seems to have broken

### ISSUE THREAD

**Issue by saikat** [Bernie-2016/ground-control#484]
From logs:

Jan 22 18:35:34 bernie-ground-control app/web.1:  backend debug Updated event:  { event_id: '44306', 
Jan 22 18:35:34 bernie-ground-control app/web.1:    event_id_obfuscated: '45bp', 
Jan 22 18:35:34 bernie-ground-control app/web.1:    event_type_id: '44', 
Jan 22 18:35:34 bernie-ground-control app/web.1:    creator_cons_id: '4415367', 
Jan 22 18:35:34 bernie-ground-control app/web.1:    contribution_page_id: null, 
Jan 22 18:35:34 bernie-ground-control app/web.1:    outreach_page_id: null, 
Jan 22 18:35:34 bernie-ground-control app/web.1:    name: 'Feel the BERN Watch Party!', 
Jan 22 18:35:34 bernie-ground-control app/web.1:    description: '<p>Just wanted to make a low-key event to watch the live stream with some friends. Feel free to bring snacks and/or booze!&nbsp;</p>', 
Jan 22 18:35:34 bernie-ground-control app/web.1:    creator_name: null, 
Jan 22 18:35:34 bernie-ground-control app/web.1:    start_day: Sat Jan 23 2016 00:00:00 GMT+0000 (UTC), 
Jan 22 18:35:34 bernie-ground-control app/web.1:    start_time: '22:00:00', 
Jan 22 18:35:34 bernie-ground-control app/web.1:    start_dt: '2016-01-23T22:00:00.000Z', 
Jan 22 18:35:34 bernie-ground-control app/web.1:    start_tz: 'US/Central', 
Jan 22 18:35:34 bernie-ground-control app/web.1:    duration: 180, 
Jan 22 18:35:34 bernie-ground-control app/web.1:    parent_event_id: '0', 
Jan 22 18:35:34 bernie-ground-control app/web.1:    venue_name: 'Kimler/Abbey House!', 
Jan 22 18:35:34 bernie-ground-control app/web.1:    venue_addr1: '2464 W Mary Dr', 
Jan 22 18:35:34 bernie-ground-control app/web.1:    venue_addr2: '', 
Jan 22 18:35:34 bernie-ground-control app/web.1:    venue_zip: '72704', 
Jan 22 18:35:34 bernie-ground-control app/web.1:    venue_city: 'Fayetteville', 
Jan 22 18:35:34 bernie-ground-control app/web.1:    venue_state_cd: 'AR                                                                                                  ', 
Jan 22 18:35:34 bernie-ground-control app/web.1:    venue_country: 'US', 
Jan 22 18:35:34 bernie-ground-control app/web.1:    venue_directions: '', 
Jan 22 18:35:34 bernie-ground-control app/web.1:    latitude: 36.123211, 
Jan 22 18:35:34 bernie-ground-control app/web.1:    longitude: -94.159683, 
Jan 22 18:35:34 bernie-ground-control app/web.1:    host_addr_addressee: null, 
Jan 22 18:35:34 bernie-ground-control app/web.1:    host_addr_addr1: null, 
Jan 22 18:35:34 bernie-ground-control app/web.1:    host_addr_addr2: null, 
Jan 22 18:35:34 bernie-ground-control app/web.1:    host_addr_zip: null, 
Jan 22 18:35:34 bernie-ground-control app/web.1:    host_addr_city: null, 
Jan 22 18:35:34 bernie-ground-control app/web.1:    host_addr_state_cd: null, 
Jan 22 18:35:34 bernie-ground-control app/web.1:    host_addr_country: 'US', 
Jan 22 18:35:34 bernie-ground-control app/web.1:    host_receive_rsvp_emails: true, 
Jan 22 18:35:34 bernie-ground-control app/web.1:    contact_phone: '479-301-3744', 
Jan 22 18:35:34 bernie-ground-control app/web.1:    public_phone: true, 
Jan 22 18:35:34 bernie-ground-control app/web.1:    capacity: 15, 
Jan 22 18:35:34 bernie-ground-control app/web.1:    closed_msg: null, 
Jan 22 18:35:34 bernie-ground-control app/web.1:    attendee_visibility: '2', 
Jan 22 18:35:34 bernie-ground-control app/web.1:    attendee_require_phone: false, 
Jan 22 18:35:34 bernie-ground-control app/web.1:    attendee_volunteer_show: 0, 
Jan 22 18:35:34 bernie-ground-control app/web.1:    attendee_volunteer_message: 'Can you volunteer at this event?', 
Jan 22 18:35:34 bernie-ground-control app/web.1:    is_official: false, 
Jan 22 18:35:34 bernie-ground-control app/web.1:    pledge_override_type: '0', 
Jan 22 18:35:34 bernie-ground-control app/web.1:    pledge_show: false, 
Jan 22 18:35:34 bernie-ground-control app/web.1:    pledge_source: null, 
Jan 22 18:35:34 bernie-ground-control app/web.1:    pledge_subsource: null, 
Jan 22 18:35:34 bernie-ground-control app/web.1:    pledge_require: false, 
Jan 22 18:35:34 bernie-ground-control app/web.1:    pledge_min: 0, 
Jan 22 18:35:34 bernie-ground-control app/web.1:    pledge_max: 0, 
Jan 22 18:35:34 bernie-ground-control app/web.1:    pledge_suggest: 0, 
Jan 22 18:35:34 bernie-ground-control app/web.1:    rsvp_use_default_email_message: true, 
Jan 22 18:35:34 bernie-ground-control app/web.1:    rsvp_email_message: null, 
Jan 22 18:35:34 bernie-ground-control app/web.1:    rsvp_email_message_html: null, 
Jan 22 18:35:34 bernie-ground-control app/web.1:    rsvp_use_reminder_email: true, 
Jan 22 18:35:34 bernie-ground-control app/web.1:    rsvp_reminder_email_sent: false, 
Jan 22 18:35:34 bernie-ground-control app/web.1:    rsvp_email_reminder_hours: 24, 
Jan 22 18:35:34 bernie-ground-control app/web.1:    rsvp_allow: '-1', 
Jan 22 18:35:34 bernie-ground-control app/web.1:    rsvp_require_signup: '-1', 
Jan 22 18:35:34 bernie-ground-control app/web.1:    rsvp_disallow_account: '-1', 
Jan 22 18:35:34 bernie-ground-control app/web.1:    rsvp_reason: null, 
Jan 22 18:35:34 bernie-ground-control app/web.1:    rsvp_redirect_url: '', 
Jan 22 18:35:34 bernie-ground-control app/web.1:    is_searchable: 0, 
Jan 22 18:35:34 bernie-ground-control app/web.1:    flag_approval: false, 
Jan 22 18:35:34 bernie-ground-control app/web.1:    chapter_id: '1', 
Jan 22 18:35:34 bernie-ground-control app/web.1:    create_dt: Fri Jan 22 2016 05:50:23 GMT+0000 (UTC), 
Jan 22 18:35:34 bernie-ground-control app/web.1:    create_app: null, 
Jan 22 18:35:34 bernie-ground-control app/web.1:    create_user: null, 
Jan 22 18:35:34 bernie-ground-control app/web.1:    modified_dt: Fri Jan 22 2016 05:50:23 GMT+0000 (UTC), 
Jan 22 18:35:34 bernie-ground-control app/web.1:    modified_app: null, 
Jan 22 18:35:34 bernie-ground-control app/web.1:    modified_user: null, 
Jan 22 18:35:34 bernie-ground-control app/web.1:    status: '1', 
Jan 22 18:35:34 bernie-ground-control app/web.1:    note: null, 
Jan 22 18:35:34 bernie-ground-control app/web.1:    geom: '010100002031BF0D00EDC5DFFE11FE63C17880571265785041' } 
Jan 22 18:35:34 bernie-ground-control app/web.1:  backend debug Making request:  {"uri":"https://go.berniesanders.com/page/api/event/update_event?api_id=odi&api_ts=1453505734&api_ver=2&api_mac=8b3ba936fd5be9ac7476312975ff932ab82a4f39","method":"POST","resolveWithFullResponse":true,"json":true,"body":"event_api_version=2&values=%7B%22event_id_obfuscated%22%3A%2245bp%22%2C%22event_type_id%22%3A%2244%22%2C%22creator_cons_id%22%3A%224415367%22%2C%22outreach_page_id%22%3Anull%2C%22name%22%3A%22Feel%20the%20BERN%20Watch%20Party!%22%2C%22description%22%3A%22%3Cp%3EJust%20wanted%20to%20make%20a%20low-key%20event%20to%20watch%20the%20live%20stream%20with%20some%20friends.%20Feel%20free%20to%20bring%20snacks%20and%2For%20booze!%26nbsp%3B%3C%2Fp%3E%22%2C%22creator_name%22%3Anull%2C%22local_timezone%22%3A%22US%2FCentral%22%2C%22venue_name%22%3A%22Kimler%2FAbbey%20House!%22%2C%22venue_addr1%22%3A%222464%20W%20Mary%20Dr%22%2C%22venue_addr2%22%3A%22%22%2C%22venue_zip%22%3A%2272704%22%2C%22venue_city%22%3A%22Fayetteville%22%2C%22venue_state_cd%22%3A%22AR%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22%2C%22venue_country%22%3A%22US%22%2C%22venue_directions%22%3A%22%22%2C%22host_addr_addressee%22%3Anull%2C%22host_addr_addr1%22%3Anull%2C%22host_addr_addr2%22%3Anull%2C%22host_addr_zip%22%3Anull%2C%22host_addr_city%22%3Anull%2C%22host_addr_state_cd%22%3Anull%2C%22host_addr_country%22%3A%22US%22%2C%22host_receive_rsvp_emails%22%3Atrue%2C%22contact_phone%22%3A%224793013744%22%2C%22public_phone%22%3Atrue%2C%22attendee_visibility%22%3A%22NONE%22%2C%22attendee_require_phone%22%3Afalse%2C%22attendee_volunteer_show%22%3A0%2C%22attendee_volunteer_message%22%3A%22Can%20you%20volunteer%20at%20this%20event%3F%22%2C%22is_official%22%3Afalse%2C%22pledge_override_type%22%3A%220%22%2C%22pledge_show%22%3Afalse%2C%22pledge_source%22%3Anull%2C%22pledge_subsource%22%3Anull%2C%22pledge_require%22%3Afalse%2C%22pledge_min%22%3A0%2C%22pledge_max%22%3A0%2C%22pledge_suggest%22%3A0%2C%22rsvp_use_default_email_message%22%3Atrue%2C%22rsvp_email_message%22%3Anull%2C%22rsvp_use_reminder_email%22%3Atrue%2C%22rsvp_reminder_email_sent%22%3Afalse%2C%22rsvp_allow%22%3A%22-1%22%2C%22rsvp_require_signup%22%3A%22-1%22%2C%22rsvp_disallow_account%22%3A%22-1%22%2C%22is_searchable%22%3A-2%2C%22flag_approval%22%3Afalse%2C%22chapter_id%22%3A%221%22%2C%22days%22%3A%5B%7B%22start_datetime_system%22%3A%222016-01-23%2016%3A00%3A00%22%2C%22duration%22%3A180%2C%22capacity%22%3A15%2C%22event_id%22%3A%2244306%22%7D%5D%7D","headers":{"content-type":"application/x-www-form-urlencoded"}} 
Jan 22 18:35:36 bernie-ground-control app/web.1:  client error (ijqbq9xe): Failure in MutationHandler 
Jan 22 18:35:36 bernie-ground-control app/web.1:  client error (ijqbq9xe): {"source":{"data":{"editEvents":null},"errors":[{"message":"{\"is_searchable\":[\"regex\"]}","locations":[{"line":1,"column":444}]}]}}

**Comment by saikat** [comment]
It actually seems like this was an instance of the person approving the event.  wonder why BSD complained?  That event type seems to allow private events.

**Comment by jlegrone** [comment]
Could not replicate.
