### ISSUE TITLE
Add plivo dialer back in

### ISSUE THREAD

**Issue by saikat** [Bernie-2016/ground-control#497]
I am 80% sure the performance issues were unrelated and that I've fixed them now.

**Comment by jlegrone** [comment]
@saikat should we still make an effort to do this?

**Comment by saikat** [comment]
It would be pretty easy to do I think and does make calling with ground control quite a bit nicer.

**Comment by jlegrone** [comment]
Great, I'll make it a low priority issue and you or someone else can feel
free to take this on at some point.
