### ISSUE TITLE
FastFwd: Pre-populate admin email address in "sender email address"

### ISSUE THREAD

**Issue by jwarnow** [Bernie-2016/ground-control#508]

**Comment by jwarnow** [comment]
@saikat can you confirm what the "sender email address" should be? i know we had talked about using something like "info@bernievolunteers.com" in case we were concerned about whitelisting, messing up our SPAM scores, etc.

**Comment by saikat** [comment]
we're sticking with @berniesanders.com email.  Sender should be a personalized one (e.g. jon@bs.com), but reply-to should be set to info@

**Comment by ejucovy** [comment]
I can look into this - for the reply-to, it looks like it's currently set to the host address: https://github.com/Bernie-2016/ground-control/blob/master/src/backend/mail.js#L184

@saikat, just want to confirm that you want that reply-to behavior changed to info@ instead -- so the host address would only be used/displayed in the email body's fake fwd?  So people wouldn't be able to just contact the host directly by hitting reply?

**Comment by saikat** [comment]
@ejucovy yup, that's right!
