### ISSUE TITLE
Implement authentication

### ISSUE THREAD

**Issue by saikat** [Bernie-2016/ground-control#51]

**Comment by saikat** [comment]
For now, we make it simple.

**Comment by jlegrone** [comment]
To create a constituent in BSD we just need an email address. I'm thinking we should ask for an email address and password, then optionally request name/zip/etc later on.

**Comment by saikat** [comment]
After some discussion with some of the others, we're going to be moving off of using BSD for authentication.  The concern is that everyone is afraid the BSD API will be too flakey to handle auth down the line, and it's a problem to start off with BSD auth and then later move to our own auth system (we can't get passwords from BSD).  So I'm changing this task to "implement our own auth".
