### ISSUE TITLE
FastFwd: Pre-populate default message

### ISSUE THREAD

**Issue by jwarnow** [Bernie-2016/ground-control#510]
maybe something like:

Hi everyone,

A local volunteer in Rochester has asked me to help her fill up a phone bank she is hosting. 

It's on [day] at [time]. You can get more info and RSVP at this link: [Event Link]

Let&#x27;s blow her away and get folks it help her out -- please sign up if you can!

Thanks,

[Admin First Name]
Bernie 2016

**Comment by jwarnow** [comment]
Worth noting that this is probably the first step, but we'll soon want to move towards #518

**Comment by bahoo** [comment]
I changed the pronouns to be gender neutral (she => they) but this is now live.
