### ISSUE TITLE
FastFwd: fix Apostrophe weirdness

### ISSUE THREAD

**Issue by jwarnow** [Bernie-2016/ground-control#512]
https://cloud.githubusercontent.com/assets/931077/12653931/b0feaa3e-c5bf-11e5-8400-c5eb94cc8431.jpg

**Comment by jwarnow** [comment]
Apostrophes are showing up as: &#x27;

**Comment by ejucovy** [comment]
I can look into this this weekend - if someone else has already been working on it just let me know.
