### ISSUE TITLE
FastFwd: Event details aren't being merged into email

### ISSUE THREAD

**Issue by jwarnow** [Bernie-2016/ground-control#513]

**Comment by ejucovy** [comment]
@jwarnow do you have a screencast or reproduction steps for this, if it's still happening/relevant?  Is the host message supposed to be templated?  (I thought it was just supposed to be pulled straight from what the host submitted without any variable content.)  Or is this related to the sender message stuff in #510 / #518?

**Comment by jwarnow** [comment]
Yeah this is related to #510 and #518
