### ISSUE TITLE
FastFwd: Randomize Staff Messages

### ISSUE THREAD

**Issue by jwarnow** [Bernie-2016/ground-control#518]
{{HostFirstName}} in in {{eventCity}} is hosting an event on {{eventDate}} and needs more people to sign up. Hope you can make it -- here's a link to the event: {{eventLink}}

----

Hey, are you free on {{eventDay}}? {{HostFirstName}} in {{eventCity}} is hosting an event on for Bernie and needs more people to sign up. Here's a link to the event: {{eventLink}}

----

There's a great Bernie volunteer event coming up near you on {{eventDay}}. {{HostFirstName}} asked me to pass along the message below -- they need more people to sign up. Here's a link where you can RSVP and get more info: {{eventLink}}

----

{{HostFirstName}} in {{eventCity}} made a special request that I forward on the message below to Bernie supporters nearby. Can you come to a volunteer event on {{eventDay}}? Here's a link to sign up and get more info:  {{eventLink}}

----

I don't usually do this, but {{HostFirstName}} in  has asked me to send out a special request to recruit more RSVPs for a Bernie volunteer event in {{eventCity}} on {{eventDay}}. Can you join in? Here's a link where you can get more info and sign up: {{eventLink}}

----

When people in the Bernie movement put out a call for help, we try to answer it. {{HostFirstName}} has asked for some help getting people to a volunteer event on {{eventDay}}. Can you join in? 
RSVP and get more info here: {{eventLink}}

----

A local volunteer in {{eventCity}} has asked for help to fill up her event. Let's blow {{HostFirstName}} away and fill this event! I included the message from {{HostFirstName}} below, and you can get details and sign up here:  {{eventLink}}

----

When someone working in this political revolution calls for some help, we try to answer.  {{HostFirstName}} needs more people to help fill up an upcoming event on {{eventDay}}. Can you join in? RSVP and get more info here: {{eventLink}}

----

Do you have plans on {{eventDay}}? There's a volunteer event for Bernie in {{eventCity}} that needs more people to fill it, and the event host asked me to pass along the message below. You can get more details and sign up here: {{eventLink}}

----

OK folks, a local volunteer for Bernie needs our help, so let's show up! {{HostFirstName}} in {{eventCity}} has asked me to forward on the message below to supporters nearby. The short version is that there's an event coming up on {{eventDay}} that needs more people to join in. You can RSVP and get more info here: {{eventLink}}

**Comment by ejucovy** [comment]
I took a stab at this in PR #538, but had a couple of questions:

* Any specific format for {{eventDay}} preferred?  I went with `Saturday, February 13, 2016 9:22 AM` since that's what's used elsewhere in the code
* Are these likely to change very often?  I stuck the list of possible messages straight in the code, but wondering if it's worth making them admin-editable through the web instead.

**Comment by jwarnow** [comment]
For format for {{eventDay}} I actually think we want it to be as casual as possible. "Saturday Feb. 13th" maybe? It should seem non-automated I think.

**Comment by saikat** [comment]
I now think that instead of randomization, we should just change up the message every few days or something.

**Comment by jwarnow** [comment]
@saikat for ease of implementation?

**Comment by jwarnow** [comment]
Because easier?
