### ISSUE TITLE
FastFwd: Add BSD Unsubscribe Link to all Ground Control e-mails and respect the unsubs

### ISSUE THREAD

**Issue by jwarnow** [Bernie-2016/ground-control#529]

**Comment by ejucovy** [comment]
I can take a stab at this over the weekend unless someone else is already working on it. 

A couple quick questions for @jwarnow and/or @saikat:

* If I'm understanding correctly, the other ground-control emails just link straight to https://go.berniesanders.com/page/unsubscribe/ without trying to merge any user details in the link or doing anything fancy.  Is that right?

* Where should the link go in the email -- above the fwd or below?

* Do you want to include the other standard footer links (update your info, receive fewer emails, contribute) too?

**Comment by jwarnow** [comment]
- Yep, straight to https://go.berniesanders.com/page/unsubscribe/

- I think put the unsubsribe link at the very bottom, below the fwd. @saikat let me know if you think otherwise. 

- My lean is to only include a simple unsubscribe link/message without the other footer links.

**Comment by saikat** [comment]
Part of this will also be actually respecting the BSD unsubscribes when sending emails from Ground Control.  That is a bit more complex and not something we are currently doing.  Agree with @jwarnow otherwise.

**Comment by jwarnow** [comment]
@saikat this frightens me "Part of this will also be actually respecting the BSD unsubscribes when sending emails from Ground Control. That is a bit more complex and not something we are currently doing. " :)

**Comment by ejucovy** [comment]
Hah, I was planning on asking where this was happening since I didn't see
it anywhere in the code. :-)

**Comment by bahoo** [comment]
This guy's out the door.
