### ISSUE TITLE
Clicking 'all day event' breaks in event creation form

### ISSUE THREAD

**Issue by saikat** [Bernie-2016/ground-control#543]

**Comment by jlegrone** [comment]
It looks like the bsd api doesn't support an all-day parameter; instead we need to set an event start and end time to mimic this behavior.

Should we simply set start time to 12am and duration 24hrs? Or accept a start time and calculate a duration that is the diff between that time and the end of the day?

**Comment by jlegrone** [comment]
Just removed the all day event option for now.
