### ISSUE TITLE
Craig report: Events not approving

### ISSUE THREAD

**Issue by saikat** [Bernie-2016/ground-control#562]
Second time I got this error, but this time i was quick enough to grab it:
4rvk: {"attendee_volunteer_show":["regex"],"is_searchable":["regex"]}

here’s what I did:
filter on phonebanks
approve all except 2
one is afundraiser. Deleted that.
last one remaining is actually a canvass. So i change event type to canvass in edit modal
click check box to leave event open
click update

**Comment by jlegrone** [comment]
The issue here is that the requirements for canvass and phonebank event types are different in BSD. The event can still be edited successfully if those conflicting values are changed by hand, but we could add logic to check values against event type before approval.

**Comment by jlegrone** [comment]
If we silently correct those errors, we may want to be careful to avoid things like making a host's phone number public, for example. Hosts might also be confused if they create an event as private but during approval have it switched to public.
