### ISSUE TITLE
Switch to auto-approval for events

### ISSUE THREAD

**Issue by saikat** [Bernie-2016/ground-control#567]
- [x] Create a pending_review flag on gc_bsd_events
- [x] Change the options for an event in the review queue to either a) Looks good b) Move to approval queue (which also marks it as reviewed) or c) Delete
- [x] Add a 'pending review' section to Admin
- [x] Make all the event types in Ground Control allow for auto-approval
- [ ] In Ground Control and BSD frontend, add a list of words that we check for and don't allow
- [x] Remove Canvass as an event type from BSD frontend and tell state staff how to make volunteer-run canvasses using ground control
- [ ] Create an e-mail that gets sent to canvass hosts and field staff whenever a new canvass event is created - https://docs.google.com/document/d/1WWqRx41azs1A-XFGC1WpIUdvC-42aI6PzrjN6-Izg2A/edit
- [x] Switch all event types in BSD to be auto-approved
- [x] Give everyone with an @berniesanders.com email address the ability to make official events

**Comment by jlegrone** [comment]
- [ ] Deploy gc changes to staging

- [ ] Run migrations

- [ ] Push to production

- [ ] Loop in Claire & Craig

- [ ] Change BSD event types to auto-approve

- [ ] Remove canvass event type from BSD frontend
