### ISSUE TITLE
Filter error in pending review

### ISSUE THREAD

**Issue by saikat** [Bernie-2016/ground-control#578]
select * from "gc_bsd_events" inner join "bsd_events" on "bsd_events"."event_id" = "gc_bsd_events"."event_id" inner join "bsd_people" on "bsd_events"."creator_cons_id" = "bsd_people"."cons_id" inner join "bsd_emails" on "bsd_events"."creator_cons_id" = "bsd_emails"."cons_id" where "gc_bsd_events"."event_id" = $1 - invalid input syntax for integer: "{"event_id":"67258"}"

**Comment by bahoo** [comment]
This is out the door.
