### ISSUE TITLE
Fix issue where onSubmit is being called on forms even if there are validation errors

### ISSUE THREAD

**Issue by saikat** [Bernie-2016/ground-control#59]
https://github.com/jquense/react-formal/issues/26

**Comment by saikat** [comment]
Specifically, it should show the validation errors when you have a completely blank form on http://localhost:3000/admin/call-assignments/create and hit submit, but instead it has an error in the console.

**Comment by saikat** [comment]
This works for now.  We should show the validation errors, though, if someone clicks submit without filling anything out.

**Comment by jlegrone** [comment]
@saikat should this be closed?

**Comment by saikat** [comment]
Yeah I think this is probably fine to close.
