### ISSUE TITLE
Prevent multiple admin FastForward submissions

### ISSUE THREAD

**Issue by jlegrone** [Bernie-2016/ground-control#651]
We should also disable the submit button as soon as it's clicked the first time and re-enable it only if there's a user input issue that prevents form submission.  Right now clicking the button multiple times or simultaneous usage from multiple admins could result in a barrage of emails.

**Comment by jlegrone** [comment]
@bahoo could you look into this? We could disable the admin initiated FFWD tool in favor of a model of first creating FastForward requests using the normal host request_email form, and then approving those requests from event admin. This gives us the benefit of the request checkout feature which we already have, and should only allow us to queue one FFWD request at a time per event.

**Comment by bahoo** [comment]
Are you seeing multiple requests come in? Multiple / subsequent submissions should just update the original request. I added it in there on the off chance that people might want to modify their original message.

See https://github.com/Bernie-2016/ground-control/blob/master/src/backend/data/schema.js#L1690:L1704

**Comment by jlegrone** [comment]
I'm seeing multiple requests in dev from the admin ffwd email generation form (different than the ffwd request approval form).

**Comment by bahoo** [comment]
This should be closed with 52fe7ac4399db8bbb79c0fc8a0bde1484f3c1b49.
