### ISSUE TITLE
http://organize.berniesanders.com 404's

### ISSUE THREAD

**Issue by ukd1** [Bernie-2016/ground-control#73]
http://sharing.rainforestqa.com/image/2v2R0J35320b - is 404'ing.

**Comment by naren8642** [comment]
Should be http://berniesanders.com/organize instead...

**Comment by saikat** [comment]
The site is not yet live as this is code that is still in active
development.

**Comment by naren8642** [comment]
Most of this stack is new to me, but if you have specific tasks, I should be able to pick it up. I would love to help Sanders 2016.
